on:
   pull_request:
     branches:
      - main
     paths:
      - 'src/**'
      - 'test/**'
      - 'setup.py'
      - 'Makefile'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout main repository
      uses: actions/checkout@v3
    - name: Create venv
      run: |
        VENV="$GITHUB_WORKSPACE/venv" PYTHON="python${{matrix.python-version}}" make venv
    - name: Install package
      run: |
        VENV="$GITHUB_WORKSPACE/venv" make install
    - name: Test with pytest
      run: |
        VENV="$GITHUB_WORKSPACE/venv" make unit-verbose
